import type { Metadata } from "next";
import "./globals.css";
import Navbar1 from "@/components/Navbar";
import Footer from "@/components/Footer";
import { CartProvider } from "@/Hooks/Context/CartContext";
import { WishlistProvider } from "@/Hooks/Context/useWishList";

import { ToastContainer } from "react-toastify";
import Loader2 from "@/components/Loader2";
import { ClerkProvider } from "@clerk/nextjs";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  loading,
}:{
  children: React.ReactNode;
  loading?: boolean;
}) {
  return (
   //@ts-expect-error getting type  error on ClerkProvider
    <ClerkProvider>
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        
      >
        {/* Show loader when page is loading */}
        {loading ? <Loader2 /> : null}
        {" "}
        <ToastContainer 
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          closeOnClick
          pauseOnHover
          draggable
          theme="light"
        />
      
      

          <CartProvider>
            <WishlistProvider>
              <Navbar1 />
              {children}
              <Footer />
            </WishlistProvider>
          </CartProvider>
       
      </body>
    </html>
    </ClerkProvider>
  );
}
